image:
  pullPolicy: IfNotPresent
  repository: codeproject/ai-server
  tag: 2.9.7
gpu12Image:
  pullPolicy: IfNotPresent
  repository: codeproject/ai-server
  tag: cuda12_2-2.9.7
gpu11Image:
  pullPolicy: IfNotPresent
  repository: codeproject/ai-server
  tag: cuda11_8-2.9.7

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 32168
        targetPort: 32168

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image

persistence:
  data:
    enabled: true
    mountPath: /etc/codeproject/ai
  downloads:
    enabled: true
    mountPath: /app/modules

portal:
  open:
    enabled: true
