image:
  pullPolicy: "IfNotPresent"
  repository: "docker.io/codercom/code-server"
  tag: "4.104.2@sha256:6edc8e2d2849749c1a1a5eff8e76563b96db407e68899c143473a6004d0a6b5a"
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    allowPrivilegeEscalation: true
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10063
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          args:
          - --user-data-dir
          - /config/.vscode
          - --auth
          - none
          env:
            PROXY_DOMAIN: ''
          probes:
            liveness:
              path: /
              type: http
            readiness:
              path: /
              type: http
            startup:
              path: /
              type: http
