image:
  pullPolicy: "IfNotPresent"
  repository: "docker.io/codercom/code-server"
  tag: "4.101.1@sha256:d53815bc6b7590a62f20a373bec4a527481b2a3439ae3635d1619d5567abb71c"
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    allowPrivilegeEscalation: true
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10063
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          args:
          - --user-data-dir
          - /config/.vscode
          - --auth
          - none
          env:
            PROXY_DOMAIN: ''
          probes:
            liveness:
              path: /
              type: http
            readiness:
              path: /
              type: http
            startup:
              path: /
              type: http
