image:
  pullPolicy: "IfNotPresent"
  repository: "docker.io/redislabs/redisinsight"
  tag: "2.70.1@sha256:1e504013982a3ac01436adcd61952453760fee470c55becaba942510a142ff7a"
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 10579
redisinsight:
  log_level: WARNING
  trusted_origins: []
  auth_prompt: false
  auth_timer: 30
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            RIPORT: "{{ .Values.service.main.ports.main.port }}"
            RIHOMEDIR: /config
            RILOGDIR: /logs
            RILOGLEVEL: "{{ .Values.redisinsight.log_level }}"
            RITRUSTEDORIGINS: '{{ join "," .Values.redisinsight.trusted_origins }}'
            RIAUTHPROMPT: "{{ .Values.redisinsight.auth_prompt }}"
            RIAUTHTIMER: "{{ .Values.redisinsight.auth_timer }}"
persistence:
  config:
    enabled: true
    mountPath: /config
  logs:
    enabled: true
    mountPath: /logs
portal:
  open:
    enabled: true
