image:
  repository: "docker.io/automaticrippingmachine/automatic-ripping-machine"
  pullPolicy: "IfNotPresent"
  tag: "2.20.4@sha256:ea3ca46d6420da8c3749680970ea4345bcc8124cb85c09c40e2f09ce79f1104b"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    allowPrivilegeEscalation: true

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 10683

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            # default media perms
            ARM_UID: "{{ .Values.securityContext.container.PUID }}"
            ARM_GID: "{{ .Values.securityContext.pod.fsGroup }}"

persistence:
  config:
    enabled: true
    mountPath: "/etc/arm/config"
  arm:
    enabled: true
    mountPath: "/home/arm"

portal:
  open:
    enabled: true
