image:
  repository: "ghcr.io/immich-app/immich-server"
  tag: "v1.132.1@sha256:71cb6d2a6587f6481ae22b1cd743c74f163acbf26ade4df890e4425bb1f2e891"
  pullPolicy: "IfNotPresent"

mlImage:
  repository: ghcr.io/immich-app/immich-machine-learning
  pullPolicy: IfNotPresent
  tag: v1.132.1@sha256:48fc9c8315a00e1856cb9dff1db626ec8c7f1e424d60a6002c7f04ce94fdfa9a

mlCudaImage:
  repository: ghcr.io/immich-app/immich-machine-learning
  pullPolicy: IfNotPresent
  tag: v1.132.1-cuda@sha256:10ff00efa6bec06d40bd904f7742d3776c38209dd595dd19cc20487c372b04c9

mlOpenvinoImage:
  repository: ghcr.io/immich-app/immich-machine-learning
  pullPolicy: IfNotPresent
  tag: v1.132.1-openvino@sha256:3c8cce8cc01e706344f340fdc3221f8322c1636455b8958137e95decd5065d27

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

immich:
  enable_ml: true
  mlImageType: mlImage
  log_level: log

service:
  main:
    # Main service targets the server
    targetSelector: main
    ports:
      main:
        port: 10323
        protocol: http
        targetSelector: main
  microservices:
    enabled: true
    type: ClusterIP
    targetSelector: microservices
    ports:
      microservices:
        enabled: true
        primary: true
        port: 10004
        protocol: http
        targetSelector: microservices
  machinelearning:
    enabled: true
    type: ClusterIP
    targetSelector: machinelearning
    ports:
      machinelearning:
        enabled: true
        primary: true
        port: 10003
        protocol: http
        targetSelector: machinelearning

persistence:
  mlcache:
    enabled: true
    type: emptyDir
    targetSelector:
      machinelearning:
        machinelearning:
          mountPath: /mlcache
  microcache:
    enabled: true
    type: emptyDir
    targetSelector:
      microservices:
        microservices:
          mountPath: /microcache
  library:
    enabled: true
    mountPath: /usr/src/app/upload/library
    targetSelector:
      # Main pod/container is server
      main:
        main: {}
      microservices:
        microservices: {}
  uploads:
    enabled: true
    mountPath: /usr/src/app/upload/upload
    targetSelector:
      # Main pod/container is server
      main:
        main: {}
      microservices:
        microservices: {}
  backups:
    enabled: true
    mountPath: /usr/src/app/upload/backups
    targetSelector:
      # Main pod/container is server
      main:
        main: {}
      microservices:
        microservices: {}
  thumbs:
    enabled: true
    mountPath: /usr/src/app/upload/thumbs
    targetSelector:
      # Main pod/container is server
      main:
        main: {}
      microservices:
        microservices: {}
  profile:
    enabled: true
    mountPath: /usr/src/app/upload/profile
    targetSelector:
      # Main pod/container is server
      main:
        main: {}
      microservices:
        microservices: {}
  video:
    enabled: true
    mountPath: /usr/src/app/upload/encoded-video
    targetSelector:
      # Main pod/container is server
      main:
        main: {}
      microservices:
        microservices: {}

cnpg:
  main:
    enabled: true
    user: immich
    database: immich
    type: vectors
    cluster:
      initdb:
        postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance;
        - CREATE SCHEMA IF NOT EXISTS vectors;
        - ALTER DATABASE immich SET search_path TO "immich", public, vectors;
        - SET search_path TO "immich", public, vectors;
        - GRANT SELECT ON TABLE pg_vector_index_stat TO PUBLIC;
        - ALTER SCHEMA vectors OWNER TO immich;

redis:
  enabled: true
  includeCommon: true
  redisUsername: default

portal:
  open:
    enabled: true

ingress:
  main:
    integrations:
      homepage:
        widget:
          version: 2
